FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
ENV ASPNETCORE_ENVIRONMENT=Development
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Debug
WORKDIR /src
COPY ["LearnHub.API/LearnHub.API.csproj", "LearnHub.API/"]
COPY ["LearnHub.Application/LearnHub.Application.csproj", "LearnHub.Application/"]
COPY ["LearnHub.Domain/LearnHub.Domain.csproj", "LearnHub.Domain/"]
COPY ["LearnHub.Infrastructure/LearnHub.Infrastructure.csproj", "LearnHub.Infrastructure/"]
RUN dotnet restore "./LearnHub.API/./LearnHub.API.csproj"
COPY . .
WORKDIR "/src/LearnHub.API"
RUN dotnet build "./LearnHub.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Debug
RUN dotnet publish "./LearnHub.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "LearnHub.API.dll"]